language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: ac4c85af-34aa-4d52-a65d-91c9f2de21e6
  app: challenge-photos
  on:
    repo: DavidDoes/fullstack-node-capstone
